// Level configuration data for all 5 levels

export const LEVELS = [
  {
    id: 1,
    name: 'Castle of Shadows',
    subtitle: '1600s Castle',
    enemyType: 'guard',
    enemyHP: 30,
    enemyDamage: 8,
    enemySpeed: 60,
    wavesCount: 5,
    enemiesPerWave: [2, 2, 3, 3, 4],
    bossHP: 240,  // 8x normal
    bossName: 'The Black Knight',
    bossType: 'boss_guard',
    bgColors: {
      sky: 0x1a1a3e,
      ground: 0x4a4a5a,
      floor: 0x555566,
    },
    decorations: ['torch', 'banner', 'stone_wall'],
  },
  {
    id: 2,
    name: 'Planet Xharkon',
    subtitle: 'Alien World',
    enemyType: 'alien',
    enemyHP: 40,
    enemyDamage: 11,
    enemySpeed: 75,
    wavesCount: 5,
    enemiesPerWave: [2, 3, 3, 4, 4],
    bossHP: 320,
    bossName: 'The Hive Queen',
    bossType: 'boss_alien',
    bgColors: {
      sky: 0x000010,
      ground: 0x2d1f4a,
      floor: 0x3d2f5a,
    },
    decorations: ['star', 'moon', 'alien_rock'],
  },
  {
    id: 3,
    name: 'Fog of London',
    subtitle: 'Victorian England',
    enemyType: 'settler',
    enemyHP: 55,
    enemyDamage: 14,
    enemySpeed: 85,
    wavesCount: 5,
    enemiesPerWave: [2, 3, 3, 4, 4],
    bossHP: 440,
    bossName: 'The Ripper',
    bossType: 'boss_settler',
    bgColors: {
      sky: 0x707080,
      ground: 0x5a5a60,
      floor: 0x6a6a72,
    },
    decorations: ['gas_lamp', 'building', 'cobblestone'],
  },
  {
    id: 4,
    name: 'Heart of the Sun',
    subtitle: 'Inside the Sun',
    enemyType: 'flame_god',
    enemyHP: 70,
    enemyDamage: 17,
    enemySpeed: 95,
    wavesCount: 5,
    enemiesPerWave: [2, 3, 4, 4, 4],
    bossHP: 560,
    bossName: 'Helios Prime',
    bossType: 'boss_flame',
    bgColors: {
      sky: 0xff6600,
      ground: 0xcc4400,
      floor: 0xdd5511,
    },
    decorations: ['solar_flare', 'plasma_pool'],
  },
  {
    id: 5,
    name: 'The Dark Kingdom',
    subtitle: 'Sinister Disneyland',
    enemyType: 'toon',
    enemyHP: 90,
    enemyDamage: 22,
    enemySpeed: 110,
    wavesCount: 5,
    enemiesPerWave: [3, 3, 4, 4, 4],
    bossHP: 720,
    bossName: 'The Dark Conductor',
    bossType: 'boss_toon',
    bgColors: {
      sky: 0x0d0010,
      ground: 0x1a0025,
      floor: 0x220030,
    },
    decorations: ['dark_castle', 'balloon', 'dark_star'],
  },
];
